export const TYPE_MOVIE_ADD="movie/add"
export const TYPE_MOVIE_DEL="movie/delete"
export const TYPE_MOVIE_UPDATE="movie/update"
export const TYPE_MOVIE_FILTER="movie/filter"
export const TYPE_UPDATE_SELECTEDID="movie/selectedID"